### ISSUE TITLE
4xH100 Training Preparation Check List

### ISSUE THREAD

**Issue by hungphongtrn** [janhq/research#14]
-  [ ] Dependencies:
       [ ] torch 2.3
       [ ] sudo
       [ ] libaio-dev
       [ ] transformers datasets deepspeed accelerate tensorboardX bitsandbytes trl peft flash-attn
       [ ] clone cutlass
       [ ] export cutlas path, cflags, ldflags, gpus
- [ ] Data: split text and sound -> push final dataset for training
- [ ] Training Code
- [ ] Accelerator Config

**Comment by tikikun** [comment]
it's done
