### ISSUE TITLE
epic: Router model

### ISSUE THREAD

**Issue by tikikun** [janhq/research#3]
Model router that will be used to decide the difficulty of the question

**Comment by tikikun** [comment]
Issues:

https://github.com/janhq/research/issues/4

**Comment by tikikun** [comment]
@hahuyhoang411 please check status and discuss whether we should go with lmsys router

**Comment by hahuyhoang411** [comment]
@tikikun with the current input as sound tokens, I think we need to train a new one. Anw, on their blog post they said they used [this data](https://huggingface.co/datasets/lmsys/lmsys-arena-human-preference-55k) for training but with some augmentation (could be synthetic new samples)

**Comment by tikikun** [comment]
we can reuse this model
