### ISSUE TITLE
Generate audio dataset with whisper-speech

### ISSUE THREAD

**Issue by tikikun** [janhq/research#6]
Using whisper-speech to convert some of the existing text dataset to audio dataset

https://github.com/collabora/WhisperSpeech

**Comment by tikikun** [comment]
@hahuyhoang411 please ask for @hiento09 help to store on our NAS once generation is done

**Comment by tikikun** [comment]
@hahuyhoang411 @hungphongtrn can you help on reporting current datasets we have? and published?

**Comment by hahuyhoang411** [comment]
full data (with audio and pretokenized using Encodec): https://huggingface.co/datasets/jan-hq/instruction-speech-v1

**Comment by hahuyhoang411** [comment]
v1.5 is currently generating (eta 5 days for 700k samples => 15 days for 2.5m samples)

**Comment by tikikun** [comment]
oh god

**Comment by hungphongtrn** [comment]
![image](https://github.com/user-attachments/assets/76b641db-d05d-4826-92f0-7c5116489307)
